In [ ]:
import numpy as np
x=np.array([1,2,3,4,2])
print(np.sort(x))

[1 2 2 3 4]


In [ ]:
y=np.array([1,2,3,4,5])
z=[True,False,True,False,True]
print(y[z])

[1 3 5]


In [ ]:
print(x.mean())
print(x.std())
print(x.var())
print(x.sum())
print(x.min())
print(x.max())

2.4
1.019803902718557
1.04
12
1
4


In [ ]:
#weighted mean
x=np.array([1,2,3,4,5])
w=np.array([1,2,3,4,5])
print(np.average(x,weights=w))

3.6666666666666665


In [ ]:
#trimmed mean
#1 2 3 4 5 6 7 8 9 10
#trim value 10%
#2 3 4 5 6 7 8 9
print(np.array([2,3,4,5,6,7,8,9]).mean())

5.5


In [ ]:
weights=np.array([.2,.3,.4,.5,.6,.7,.8,.9])
print(np.sum(weights))
np.cumsum(weights)

4.4


array([0.2, 0.5, 0.9, 1.4, 2. , 2.7, 3.5, 4.4])

In [ ]:
#trimmed mean
#1 2 3 4 5 6 7 8 9 10
#trim value 10%
#2 3 4 5 6 7 8 9
x=np.arange(1,10)
print(x)
y=x/10
print(y)
trim_len=int(len(x)/10)+1
print(trim_len)
x=x[trim_len:len(x)-trim_len]
print(x)
print(np.mean(x))

[1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
1
[2 3 4 5 6 7 8]
5.0


In [ ]:
#excercise 1
store1_sales=np.array([10,15,20,13,17])
store2_sales=np.array([12,18,25,11,16])

In [ ]:
#element wise sum
print(np.add(store1_sales,store2_sales))

[22 33 45 24 33]


In [ ]:
print(np.multiply(store1_sales,store2_sales))

[120 270 500 143 272]


In [ ]:
print(np.subtract(store1_sales,store2_sales))


[-2 -3 -5  2  1]


In [ ]:
print(np.sum(store1_sales+store2_sales))

157


In [ ]:
angles=np.array([0,30,45,60,90])
num=np.array([24,36,18,48,60])
num2=np.array([18,60,24,36,12])
np.deg2rad(angles)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.sin(np.deg2rad(angles))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.cos(np.deg2rad(angles))

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
np.gcd(num,num2)

array([ 6, 12,  6, 12, 12])

In [ ]:
np.lcm(num,num2)

array([ 72, 180,  72, 144,  60])

In [ ]:
np.gcd.reduce(num)
np

6

In [ ]:
np.lcm.reduce(num2)

360

In [ ]:
np.lcm(np.lcm.reduce(num),np.lcm.reduce(num2))

720

In [ ]:
np.gcd(np.gcd.reduce(num),np.gcd.reduce(num2))

6

#pandas


In [ ]:
pip install pandas

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2


In [ ]:
#data structures and i/o operations
#seris-1D array, data frame-2D array
a=pd.series([1,2,3,4,5])
print(a)

AttributeError: module 'pandas' has no attribute 'series'

In [ ]:
df=pd.read_csv('/car_data.csv')
print(df.to_string())

     city_mpg                           class  combination_mpg  cylinders  displacement drive    fuel_type  highway_mpg               make                                  model transmission  year
0          25                     midsize car               29        4.0           2.5   fwd          gas           36              mazda                                      6            m  2014
1          26                     midsize car               30        4.0           2.5   fwd          gas           37              mazda                                      6            a  2014
2          25     small sport utility vehicle               27        4.0           2.5   fwd          gas           31              mazda                               cx-5 2wd            a  2014
3          26     small sport utility vehicle               29        4.0           2.0   fwd          gas           34              mazda                               cx-5 2wd            m  2014
4          26  

In [ ]:
a=[1,2,3]
a=pd.Series(a)
print(a)
#

0    1
1    2
2    3
dtype: int64


In [ ]:
#customise indexing
a=[2,4,5]
a=pd.Series(a,index=['a1','a2','a3'])
print(a)

a1    2
a2    4
a3    5
dtype: int64


In [ ]:
print(df[4:5])
print(df.loc[4])

   city_mpg                        class  combination_mpg  cylinders  \
4        26  small sport utility vehicle               28        4.0   

   displacement drive fuel_type  highway_mpg   make     model transmission  \
4           2.0   fwd       gas           32  mazda  cx-5 2wd            a   

   year  
4  2014  
city_mpg                                    26
class              small sport utility vehicle
combination_mpg                             28
cylinders                                  4.0
displacement                               2.0
drive                                      fwd
fuel_type                                  gas
highway_mpg                                 32
make                                     mazda
model                                 cx-5 2wd
transmission                                 a
year                                      2014
Name: 4, dtype: object


In [ ]:
df.loc[4,"fuel_type"]

'gas'

In [ ]:
df.head()

city_mpg                        class  combination_mpg  cylinders  \
0        25                  midsize car               29        4.0   
1        26                  midsize car               30        4.0   
2        25  small sport utility vehicle               27        4.0   
3        26  small sport utility vehicle               29        4.0   
4        26  small sport utility vehicle               28        4.0   

   displacement drive fuel_type  highway_mpg   make     model transmission  \
0           2.5   fwd       gas           36  mazda         6            m   
1           2.5   fwd       gas           37  mazda         6            a   
2           2.5   fwd       gas           31  mazda  cx-5 2wd            a   
3           2.0   fwd       gas           34  mazda  cx-5 2wd            m   
4           2.0   fwd       gas           32  mazda  cx-5 2wd            a   

   year  
0  2014  
1  2014  
2  2014  
3  2014  
4  2014

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   city_mpg         550 non-null    int64  
 1   class            550 non-null    object 
 2   combination_mpg  550 non-null    int64  
 3   cylinders        548 non-null    float64
 4   displacement     548 non-null    float64
 5   drive            550 non-null    object 
 6   fuel_type        550 non-null    object 
 7   highway_mpg      550 non-null    int64  
 8   make             550 non-null    object 
 9   model            550 non-null    object 
 10  transmission     550 non-null    object 
 11  year             550 non-null    int64  
dtypes: float64(2), int64(4), object(6)
memory usage: 51.7+ KB


In [ ]:
data={"country":["india","china","usa"],"population":[100,234,233],"Area":[200,123,345],"Gdp":[123,345,567]}
dp=pd.DataFrame(data)
print(dp)

  country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567


In [ ]:
print(dp['population'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: population
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes
None


In [ ]:
dp.head(5)

country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567

In [ ]:
dp['Gdp'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: Gdp
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes


In [ ]:
dp.tail(5)

country  population  Area  Gdp
0   india         100   200  123
1   china         234   123  345
2     usa         233   345  567

In [ ]:
dp.loc[1,'country']=None
dp

country  population  Area  Gdp
0   india         100   200  123
1    None         234   123  345
2     usa         233   345  567

In [ ]:
dp=dp.dropna() #creates a temp deletion

In [ ]:
dp

country  population  Area  Gdp
0   india         100   200  123
2     usa         233   345  567

In [ ]:
#adding new columns
dp['cddf']=pd.Series(['fdf','sfdsd'],index=[0,2])

<ipython-input-68-6306a5b36be5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp['cddf']=pd.Series(['fdf','sfdsd'],index=[0,2])


In [ ]:
dp

country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd

In [ ]:
#permanent deletion
dp.dropna(inplace=True)

<ipython-input-70-d156ad3d4363>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp.dropna(inplace=True)


In [ ]:
dp

country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd

In [ ]:
#fill null values
dp.fillna(100,inplace=True)

<ipython-input-72-97f757ff262c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dp.fillna(100,inplace=True)


In [ ]:
dp

country  population  Area  Gdp   cddf
0   india         100   200  123    fdf
2     usa         233   345  567  sfdsd